# Generated by Django 2.2.1 on 2019-06-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='osoba',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='maile', to='phone_book_app.Osoba'),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='osoba',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefony', to='phone_book_app.Osoba'),
        ),
    ]
