# Generated by Django 2.2.1 on 2019-06-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book_app', '0002_auto_20190610_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='osoba',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maile', to='phone_book_app.Osoba'),
        ),
    ]
